# Generated by Django 4.1.7 on 2023-04-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_transaction_created_at_transaction_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_stock', 'На складе'), ('sold', 'Продан'), ('written_off', 'Списан'), ('returned', 'Возвращен')], default='in_stock', max_length=20),
        ),
    ]
