# Generated by Django 4.1.7 on 2023-04-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_is_returned_product_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplyTransaction',
        ),
    ]
