# Generated by Django 4.1.7 on 2023-04-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_creditpayment_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditsale',
            old_name='total_amount',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='creditsale',
            name='paid_off',
        ),
        migrations.RemoveField(
            model_name='creditsale',
            name='term_months',
        ),
        migrations.AddField(
            model_name='creditsale',
            name='credit_months',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='customer_email',
            field=models.EmailField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='customer_name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='customer_phone',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='contract_number',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
    ]
