# Generated by Django 4.1.7 on 2023-05-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_product_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditsale',
            name='product',
        ),
        migrations.AddField(
            model_name='creditsale',
            name='products',
            field=models.ManyToManyField(to='inventory.product', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_stock', 'На складе'), ('sold', 'Продан'), ('written_off', 'Списан'), ('returned', 'Возвращен')], default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALE', 'Продажа'), ('RETURN', 'Возврат'), ('WRITE_OFF', 'Списание')], max_length=50, verbose_name='Тип операции'),
        ),
    ]
