# Generated by Django 4.1.7 on 2023-05-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_creditsale_product_creditsale_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditsale',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
