# Generated by Django 4.1.7 on 2023-05-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_transaction_product_transaction_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_returned',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_returned',
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('U', 'Унисекс')], default='U', max_length=1),
        ),
    ]
