# Generated by Django 4.1.7 on 2023-05-02 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_product_is_returned_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='credit_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.creditsale', verbose_name='Кредитная продажа'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Общая сумма'),
        ),
    ]
