# Generated by Django 4.1.7 on 2023-05-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_transaction_credit_sale_transaction_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_stock', 'На складе'), ('sold', 'Продан'), ('written_off', 'Списан')], default='in_stock', max_length=20),
        ),
    ]
