# Generated by Django 4.1.7 on 2023-05-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский'), ('У', 'Унисекс')], default='У', max_length=1),
        ),
    ]
