# Generated by Django 4.1.7 on 2023-05-03 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
