# Generated by Django 4.1.7 on 2023-05-04 14:26

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_of_manufacture',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Страна производителя'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
